eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://iam-test.jaza-soft.com/.well-known/jwks.json
          issuer-uri:  # Leave this EMPTY (not used)

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans