eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

server:
  tomcat:
    threads:
      max: 10000

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: product-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://micro-postgres:5432/product_service
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://iam-test.jaza-soft.com/.well-known/jwks.json
          issuer-uri:  # Leave this EMPTY (not used)

management:
  tracing:
    enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.web.client: INFO

logstash:
  enabled: false
  host: logstash
  port: 5044